### ISSUE TITLE
Result class does not work

### ISSUE THREAD

**Issue by joomartin** [Takachi67/vue3-autocomplete#1]
You have a typo in the computed functions. It returns `props.resultsContainerClass.length` instead of `props.resultsContainerClass` itself. Same thing for `props.resultsItemClass`

**Comment by Takachi67** [comment]
Thanks for commenting. Fix is now deployed.

**Comment by maegnes** [comment]
After the installation via npm I'm still facing this issue though I can see the fix in the repository. :-(
