### ISSUE TITLE
Can't set the selected value.

### ISSUE THREAD

**Issue by ujjwol05** [Takachi67/vue3-autocomplete#10]
![image](https://user-images.githubusercontent.com/12679426/116100943-c147c480-a6f0-11eb-842d-a619b33c826f.png)

Once the value is clicked, no value is being set to the input element but is inserted into the div container as a value.

Please refer to the image.

**Comment by ujjwol05** [comment]
The selected value "27 BRADMAN AVENUE ST CLAIR 2759" should have come in the input field. 

But after selecting from the search box, it appears in the div element rather than on the input box.

**Comment by blwasham** [comment]
I think adding a v-bind="{...$attrs} to your input would solve both this issue and the placeholder issue that is open, no?

**Comment by Takachi67** [comment]
Hey, this is a great idea, but I don't have any time to do this properly. I'd love to accept any PR that make this change properly. :)
