### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by ingridgrenholm** [Takachi67/vue3-autocomplete#13]
How do I implement a placeholder? My component looks like this at the moment:

    <Autocomplete
      @input="Elements"
      :results="myElements"
      :display-item="displayElement"
      :max="15"
      @onSelect="onSelected"
    ></Autocomplete>

**Comment by panos4tw** [comment]
Created a pull request for it https://github.com/Takachi67/vue3-autocomplete/pull/15

**Comment by Takachi67** [comment]
Hi, I added the feature. Thanks for the support.
