### ISSUE TITLE
How do I display the selected  value...?

### ISSUE THREAD

**Issue by panos4tw** [Takachi67/vue3-autocomplete#14]
It's probably a silly question, but after I have selected a value and fired the event (where I can see I got the proper value) the inputbox still displays the few letters that I have typed instead of the full value, eg if autocompleting for countries it will display "Arge" after I have already selected Argentina.

I am missing something obvious right...?

Here's a sample of the code:

       <div class="search-box">
          <Autocomplete class="search-bar" @input="getItems" :results="CurrentItems" results-item-class = "search-bar" @onSelect="ItemSelected" :display-item="DisplayItem" v-model="query" v-on:keyup.enter="fetchWeather"> </Autocomplete>
       </div>

__________________________________

  methods:{
    DisplayItem (value) {
      return value.name +" - " +value.country;
    },
    ItemSelected (value) {
      this.selected = value.name +" - " +value.country;
    },
     async getItems(value){
       console.log(value);
     this.CurrentItems = this.Items.filter( element => element.name.substring(0,value.length) ==value);
     this.CurrentItems = Object.values(this.CurrentItems);

    }

**Comment by matthiasvanwoensel** [comment]
I'm also stuck on this... Any who can help?

**Comment by shane9** [comment]
I used a ref attribute.

` <Autocomplete @input="getSuggestions"
                             @onSelect="setResult"
                              :results="results"
                              ref="autocomplete"></Autocomplete>`

`ItemSelected(value) {
    this.selected = value;
    this.$refs.autocomplete.searchText = value;
}`

**Comment by Takachi67** [comment]
Hey ! New feature, you can use refs as @shane9 said and I added a method "setText(value)" which will update the text inside the input.
