### ISSUE TITLE
Axios dependency has a security vulnerability

### ISSUE THREAD

**Issue by LuisMiguelFilipe** [Takachi67/vue3-autocomplete#3]
Axios dependency `^0.20.0`  has a known security vulnerability.

We should upgrade to the latest version

Since `Axios` has a zero-based version we could define our dependency as
```
"axios": ">=0.2.0 <1"
```

**Comment by LuisMiguelFilipe** [comment]
I am happy to create a PR myself but i can only do that later

**Comment by Takachi67** [comment]
I'll be happy to accept your PR after my local tests. :)
