### ISSUE TITLE
Maximum call stack size exceeded    

### ISSUE THREAD

**Issue by ingridgrenholm** [Takachi67/vue3-autocomplete#6]
Hi!
I get the error message: Maximum call stack size exceeded at Module.eval [as isFunction], when I use your autocomplete-plugin. I think it has something to do with the TimeOut, but Im not sure.

**Comment by Takachi67** [comment]
Hi, can you show me the error ? Never had this issue. Thanks.

**Comment by ingridgrenholm** [comment]
Can I include a placeholder in the search box?
