### ISSUE TITLE
How to position the result below the input ?

### ISSUE THREAD

**Issue by dominique-bureau** [Takachi67/vue3-autocomplete#8]
Hi Takachi67

Hope you are fine first. 

I just tried your module "vue3-autocomplete". I like it because it is very simple ! Thanks for it. 

But I have a problem for the position of the result. See the picture :

<img width="189" alt="2021-04-18_08h58_05" src="https://user-images.githubusercontent.com/33835828/115137167-c20f9500-a024-11eb-9c3a-8ca2559cb726.png">

How to position the result just below the input ? I am a very beginner in vue.js , certainly it is very basic but I do not know how to do that. 

But perhaps you do not maintain this module ?
Have a nice day.

Dom

**Comment by Takachi67** [comment]
Hi,

As the documentation says, you can pass classes to the component for the input and the results, then you can add the css you want to theses classes.

Prop for class for input : input-class
Prop for class for results : results-container-class

Thanks for using my component. :)
