### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by ingridgrenholm** [Takachi67/vue3-autocomplete#9]
Can I include a placeholder in the search box?

**Comment by Takachi67** [comment]
Sorry I really missed that. I'll implement a global **attr** property ASAP.

**Comment by ingridgrenholm** [comment]
Please, Ping me when its done :)

**Comment by blwasham** [comment]
Global $attr property has been added to the input and merged to main. Just waiting on new version to be published to npm

**Comment by DaisyPonraj** [comment]
Hi.. Have u updated the npm regards Placeholder issue???.
